spring:
  application:
    name: fleet-management-system-core
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:54323/agrostoc_fms}
    username: ${DATABASE_USERNAME:agrostoc}
    password: ${DATABASE_PASSWORD:agrostoc}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8091
